version: '3'
services:
  flask:
    image: test
    # Путь до Dockerfile
    build: ./main
    # Имя для создаваемого контейнера
    container_name: main-flask
    # Создание переменных окружения в контейнере
    environment:
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True                   
      ##
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./main:/main
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    command: python main.py